version: "3"
services:
  odoo:
    build: .
    networks:
      - local_network
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - ./src-odoo:/src-odoo
      - ./config:/etc/config
    depends_on:
      - postgresql
    env_file:
      - ./.envs/.local/.postgresql
      - ./.envs/.local/.odoo
    command: /start

  postgresql:
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.envs/.local/.postgresql
    networks:
      - local_network

  nginx:
    image: nginx:1.22
    volumes:
      - ./compose/nginx/templates:/etc/nginx/templates
    networks:
      - local_network
    ports:
      - "80:80"
    depends_on:
      - odoo
    environment:
      - HOSTNAME=localhost
      - SERVER_ODOO=odoo

  mailhog:
    image: mailhog/mailhog
    container_name: 'mailhog'
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - local_network

volumes:
  postgres_data:
  odoo_filestore:

networks:
  local_network:
    driver: bridge
