#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Input: /etc/config/odoo-server.conf
# Output: /etc/config/env-odoo-server.conf (after variable substitution)
rm /etc/config/env-odoo-server.conf > /dev/null
envsubst < /etc/config/odoo-server.conf > /etc/config/env-odoo-server.conf

python ./odoo-bin -c /etc/config/env-odoo-server.conf

